### ISSUE TITLE
Save the publication date in sitemap always in W3C Format

### ISSUE THREAD

**Issue by CarolineGeven** [Yoast/wpseo-news#112]
Instead of saving the local publication date in the sitemap, save the UTC standard. This way the publication date is a standard and is always sent to Google the correct way.

**Comment by amboutwe** [comment]
From support request: "I don't think that your interpretation of [Google article](https://support.google.com/news/publisher/answer/74288?hl=en) is correct. It writes "Article publication date in [W3C format](http://www.w3.org/TR/NOTE-datetime), using either the "complete date" format (YYYY-MM-DD) or the "complete date plus hours, minutes and seconds" format with time zone designator (YYYY-MM-DDThh:mm:ssTZD) format", which means you must indicate local time publication date and not UTC time. I'm sure about that because I had discussions in the past with Google News support about that."

**Comment by monbauza** [comment]
Please inform the customer of conversation # 119505 when this conversation has been closed.

**Comment by monbauza** [comment]
![image](https://cloud.githubusercontent.com/assets/9658774/15283113/45a9c0dc-1b48-11e6-9455-5288971adf7f.png)

**Comment by monbauza** [comment]
Please inform the customer of conversation # 120950 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 130807 when this conversation has been closed.

**Comment by omarreiss** [comment]
We should also throw a notification when News SEO is installed and no timezone was set in WordPress.
