### ISSUE TITLE
When editing post from quick edit, editor's pick checkbox is reset

### ISSUE THREAD

**Issue by jdevalk** [Yoast/wpseo-news#196]
To reproduce:
- Create a new post, check the editor's pick checkbox, publish
- Edit the title from quick edit, save
- Go into the post or check in DB: editor's pick checkbox is unset

**Comment by jdevalk** [comment]
Please inform the customer of conversation # 103153 when this conversation has been closed.

**Comment by benvaassen** [comment]
Please inform the customer of conversation # 155804 when this conversation has been closed.

**Comment by afercia** [comment]
Tested a bit and as far as I see this happens also for other checkboxes, eg.:
Exclude from News Sitemap
Use the standout tag

**Comment by afercia** [comment]
Seems to me when saving the WP SEO metadata, [at this point](https://github.com/Yoast/wordpress-seo/blob/4a862e42280d7c16ad6edbd08cad9af3a491015c/admin/metabox/class-metabox.php#L799) we should check if the post action is `inline-save` in order to don't try to save checkboxes values that are not present in the quick edit form.

**Comment by afercia** [comment]
Hm or maybe the whole thing should not run when the post is submitted from the quick edit?
