### ISSUE TITLE
Sitemap Does Not Include CPT Items Created With 'Toolset Types' Plugin

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-news#215]
**Current Outcome:**
Sitemap is empty.

**Expected Outcome:**
Sitemap would include items within CPTs.

**Steps to Reproduce**
1. Install [Toolset Types](https://wordpress.org/plugins/types/) plugin along with Yoast SEO (free or prem) and News SEO.
2. Create a CPT with Toolset Types using default values. I created an Articles CPT.
3. Create new post in the CPT.
4. Set News SEO to include CPT.
5. View sitemap. <- Empty

**Versions**
* WordPress 4.5.2
* Yoast SEO 3.2.5 (free or prem)
* News SEO 3.2
* Toolset Types 2.0.1
* Theme: Twenty Sixteen 1.2

**Other Info**
* The same content in a default post type is displayed in the news sitemap if 'Post' is scanned.
* The CPT sitemap includes the item.
* This has **not** been reported to the Toolset Types developer.

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 120234 when this conversation has been closed.

**Comment by boblinthorst** [comment]
This issue seems to be caused by unfortunate timing. 

The Toolset types plugin doesn't seem to immediately register the new post types. The news-seo function however, needs the information before it is made available by the toolset plugin. 

The custom post types are only available after toolset types is done 'creating' them. For that reason, both the news sitemap and the seo-news tab in the seo metabox are missing on the custom post types created by toolset types. Because at the time of calling the get_post_types method they both use, the added custom post types won't be found yet. However, the custom post types do exist at the creation of the checkboxes to see which post types should be added to the news sitemap.

Possible solutions to this issue:
- See if the timing of toolset types can be made earlier, 
- Somehow make the news-seo hook later.

**Comment by omarreiss** [comment]
The toolset types plugin is basically hooking to late. Nothing we can do about it. The customer should contact toolset types support.
