### ISSUE TITLE
Two news sitemap entries in the sitemap_index

### ISSUE THREAD

**Issue by atimmer** [Yoast/wpseo-news#251]
### What did you expect to happen?

I have only one entry in the `sitemap_index.xml` for the news sitemap.

### What happened instead?

I have two entries in my `sitemap_index.xml`:
* `news-sitemap.xml`
* `yoast-news-sitemap.xml`

### How can we reproduce this behavior?

* Have a post type that has `news` as a slug.
* Flush the rewrite rules.
* Go to the `sitemap_index.xml`.

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version: 4.6
* Yoast SEO version: 3.5
* News SEO version: 3.5

**Comment by tacoverdo** [comment]
Why do you feel this isn't intended behavior?

When you have a post type `News`, and it has a sitemap, it will be `news-sitemap.xml`. So that is correct. 
If you then enable News SEO, it will change its sitemap from the default `news-sitemap.xml` to `yoast-news-sitemap.xml` to prevent a conflict with the sitemap of the Post Type `News`.

That would lead to you seeing both a `news-sitemap.xml` and a `yoast-news-sitemap.xml`.

**Comment by atimmer** [comment]
Ah I see.
