### ISSUE TITLE
Version constant not updating on `grunt update-version`

### ISSUE THREAD

**Issue by Xyfi** [Yoast/wpseo-news#516]
### What did you expect to happen?
When running `grunt set-version --new-version=XX.XX-RCX` followed by `grunt update-version`, I expect the line in `wpseo-news.php` that holds the plugin's version constant to be updated too. Currently it's stuck at `11.3` while version `11.7` has been released.

This constant was first introduced in https://github.com/Yoast/wordpress-seo/pull/13133/files, and isn't used yet, but we should fix this for the future.

### What happened instead?
It did not.

### How can we reproduce this behavior?
1. Run `grunt set-version --new-version=12.34-RC56`
2. Run `grunt update-version`
3. Notice that the version has been set in the `package.json`'s `version` and in the comment at the top of `wpseo-news.php`, but not in the constant in `wpseo-news.php` (`WPSEO_NEWS_VERSION`).

Can you provide a link to a page which shows this issue?
https://github.com/Yoast/wpseo-news/blob/trunk/wpseo-news.php#L40

### Technical info
* WordPress version: 5.2.2
* Yoast SEO version: 11.7

**Comment by IreneStr** [comment]
The problem is in this regex:
https://github.com/Yoast/plugin-grunt-tasks/blob/fd2c4510c83d8df7392f0a3712fd8c252317917a/config/update-version.js#L27.

The `<%= pluginVersionConstant %>` part is not replaced in the regex, which means it's looking for `<%= pluginVersionConstant %>` literally in `wpseo-news.php`.

If you replace `define( 'WPSEO_NEWS_VERSION', '11.3' );` by `define( '<%= pluginVersionConstant %>', '11.7-RC2' );` in https://github.com/Yoast/wpseo-news/blob/trunk/wpseo-news.php#L40
it does update the version number.
